import { AlgorithmInfo } from '../types';

export const ALGORITHMS: AlgorithmInfo[] = [
  // 排序
  {
    id: 'bubbleSort',
    name: '冒泡排序',
    category: 'sort',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    stable: true,
    description: '通过两两比较相邻元素并交换，使较大元素逐渐冒泡到数组末端。',
    code: [
      'for i = 0 to n-1:',
      '    for j = 0 to n-i-2:',
      '        if arr[j] > arr[j+1]:',
      '            swap(arr[j], arr[j+1])',
    ],
    tips: '最好情况 O(n) 在已排序时可通过 flag 优化',
  },
  {
    id: 'quickSort',
    name: '快速排序',
    category: 'sort',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)' },
    stable: false,
    description: '选择基准元素，将数组分为两部分递归排序。',
    code: [
      'function quickSort(arr, low, high):',
      '    if low < high:',
      '        pivot = partition(arr, low, high)',
      '        quickSort(arr, low, pivot-1)',
      '        quickSort(arr, pivot+1, high)',
    ],
    tips: '基准选择可用三数取中法避免最坏情况',
  },
  {
    id: 'insertionSort',
    name: '直接插入排序',
    category: 'sort',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    stable: true,
    description: '将数组分为已排序和未排序两部分，逐个将未排序元素插入已排序区。',
    code: [
      'for i = 1 to n-1:',
      '    key = arr[i]',
      '    j = i - 1',
      '    while j >= 0 and arr[j] > key:',
      '        arr[j+1] = arr[j]',
      '        j = j - 1',
      '    arr[j+1] = key',
    ],
    tips: '对近乎有序的数组效率接近 O(n)',
  },
  {
    id: 'selectionSort',
    name: '简单选择排序',
    category: 'sort',
    complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' },
    stable: true,
    description: '每轮从未排序区选出最小元素，放到已排序区末尾。',
    code: [
      'for i = 0 to n-1:',
      '    minIdx = i',
      '    for j = i+1 to n-1:',
      '        if arr[j] < arr[minIdx]:',
      '            minIdx = j',
      '    swap(arr[i], arr[minIdx])',
    ],
    tips: '交换次数少，最多 n-1 次',
  },
  {
    id: 'shellSort',
    name: '希尔排序',
    category: 'sort',
    complexity: { best: 'O(n log n)', average: 'O(n^1.3)', worst: 'O(n²)' },
    stable: false,
    description: '基于插入排序的分组优化，通过逐步缩小增量提升排序效率。',
    code: [
      'gap = n / 2',
      'while gap > 0:',
      '    for i = gap to n-1:',
      '        temp = arr[i]',
      '        j = i',
      '        while j >= gap and arr[j-gap] > temp:',
      '            arr[j] = arr[j-gap]',
      '            j = j - gap',
      '        arr[j] = temp',
      '    gap = gap / 2',
    ],
  },
  {
    id: 'mergeSort',
    name: '归并排序',
    category: 'sort',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' },
    stable: true,
    description: '分治策略，将数组递归拆分再合并，保证稳定性。',
    code: [
      'function mergeSort(arr):',
      '    if len(arr) <= 1: return arr',
      '    mid = len(arr) / 2',
      '    left = mergeSort(arr[:mid])',
      '    right = mergeSort(arr[mid:])',
      '    return merge(left, right)',
    ],
  },
  {
    id: 'heapSort',
    name: '堆排序',
    category: 'sort',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' },
    stable: false,
    description: '利用堆这种完全二叉树结构，每次取出堆顶最大/最小值完成排序。',
    code: [
      'buildMaxHeap(arr)',
      'for i = n-1 down to 1:',
      '    swap(arr[0], arr[i])',
      '    heapify(arr, 0, i)',
    ],
  },
  {
    id: 'radixSort',
    name: '基数排序',
    category: 'sort',
    complexity: { best: 'O(d(n+r))', average: 'O(d(n+r))', worst: 'O(d(n+r))' },
    stable: true,
    description: '按位数逐个分配收集，从低位到高位进行多轮排序。',
    code: [
      'for each digit from LSD to MSD:',
      '    distribute elements into buckets[0-9]',
      '    collect elements from buckets',
    ],
    tips: '仅适用于非负整数',
  },
  // 查找
  {
    id: 'linearSearch',
    name: '顺序查找',
    category: 'search',
    complexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)' },
    description: '从数组一端逐个比对元素，直到找到目标或遍历结束。',
    code: [
      'for i = 0 to n-1:',
      '    if arr[i] == target:',
      '        return i',
      'return -1',
    ],
  },
  {
    id: 'binarySearch',
    name: '二分查找',
    category: 'search',
    complexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(log n)' },
    description: '在有序数组中，通过每次折半缩小搜索区间来定位目标。',
    code: [
      'low = 0, high = n-1',
      'while low <= high:',
      '    mid = (low + high) / 2',
      '    if arr[mid] == target: return mid',
      '    if arr[mid] < target: low = mid + 1',
      '    else: high = mid - 1',
      'return -1',
    ],
    tips: '仅适用于有序数组',
  },
  // ==================== 树 ====================
  {
    id: 'bstInsert',
    name: 'BST 插入',
    category: 'tree',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(n)' },
    description: '向二叉搜索树中插入新节点，保持左子树小于根、右子树大于根的性质。',
    code: [
      'function insert(root, key):',
      '    if root is null:',
      '        return Node(key)',
      '    if key < root.val:',
      '        root.left = insert(root.left, key)',
      '    else:',
      '        root.right = insert(root.right, key)',
      '    return root',
    ],
    tips: '最坏情况退化为链表（有序插入）',
  },
  {
    id: 'bstSearch',
    name: 'BST 查找',
    category: 'tree',
    complexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(n)' },
    description: '在二叉搜索树中查找目标值，利用左小右大的性质每次折半。',
    code: [
      'function search(root, key):',
      '    if root is null: return null',
      '    if key == root.val: return root',
      '    if key < root.val:',
      '        return search(root.left, key)',
      '    return search(root.right, key)',
    ],
  },
  {
    id: 'inorder',
    name: '中序遍历',
    category: 'tree',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    description: '遍历顺序：左子树 → 根节点 → 右子树， BST 中序遍历结果为有序序列。',
    code: [
      'function inorder(node):',
      '    if node is null: return',
      '    inorder(node.left)',
      '    visit(node)',
      '    inorder(node.right)',
    ],
    tips: '中序遍历 BST 得到升序序列',
  },
  {
    id: 'preorder',
    name: '前序遍历',
    category: 'tree',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    description: '遍历顺序：根节点 → 左子树 → 右子树，常用于复制树结构。',
    code: [
      'function preorder(node):',
      '    if node is null: return',
      '    visit(node)',
      '    preorder(node.left)',
      '    preorder(node.right)',
    ],
    tips: '前序遍历适合树的复制与序列化',
  },
  {
    id: 'postorder',
    name: '后序遍历',
    category: 'tree',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    description: '遍历顺序：左子树 → 右子树 → 根节点，常用于删除树或求表达式。',
    code: [
      'function postorder(node):',
      '    if node is null: return',
      '    postorder(node.left)',
      '    postorder(node.right)',
      '    visit(node)',
    ],
    tips: '后序遍历适合释放树的内存',
  },
  // ==================== DFS / BFS / 层序遍历（三合一）====================
  {
    id: 'dfs',
    name: 'DFS 深度优先',
    category: 'tree',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    description: '深度优先遍历：使用栈结构，先深入再回溯，支持前序/中序/后序三种顺序。',
    code: [
      'function dfs(root, mode="preorder"):',
      '    stack = [root]',
      '    while stack not empty:',
      '        node = stack.pop()',
      '        visit(node)',
      '        if node.right: stack.push(node.right)',
      '        if node.left: stack.push(node.left)',
    ],
    tips: 'DFS 用栈模拟递归，空间复杂度 O(h)，h 为树高',
  },
  {
    id: 'bfs',
    name: 'BFS 广度优先',
    category: 'tree',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    description: '广度优先遍历：使用队列，按层次从根到叶子逐层访问，每层从左到右。',
    code: [
      'function bfs(root):',
      '    queue = [root]',
      '    while queue not empty:',
      '        node = queue.dequeue()',
      '        visit(node)',
      '        if node.left: queue.enqueue(node.left)',
      '        if node.right: queue.enqueue(node.right)',
    ],
    tips: 'BFS 用队列实现，空间复杂度 O(w)，w 为最大宽度',
  },
  {
    id: 'levelorder',
    name: '层序遍历',
    category: 'tree',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    description: '层序遍历：按层级顺序输出二叉树节点，同一层从左到右，清晰展示树的层次结构。',
    code: [
      'function levelOrder(root):',
      '    queue = [root]',
      '    level = 0',
      '    while queue not empty:',
      '        print("第", level+1, "层")',
      '        for i in range(len(queue)):',
      '            node = queue.dequeue()',
      '            visit(node)',
      '            if node.left: queue.enqueue(node.left)',
      '            if node.right: queue.enqueue(node.right)',
      '        level += 1',
    ],
    tips: '层序遍历分组展示各层节点，辅助理解树的层次结构',
  },
  // ==================== 平衡二叉树 ====================
  {
    id: 'avlInsert',
    name: 'AVL 树插入',
    category: 'tree',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(log n)' },
    description: '自平衡二叉搜索树，通过旋转操作保持左右子树高度差不超过 1，查找效率稳定。',
    code: [
      'function insert(root, key):',
      '    // BST 插入',
      '    root = bstInsert(root, key)',
      '    // 更新高度，检查平衡因子',
      '    bf = height(left) - height(right)',
      '    if |bf| > 1:',
      '        // LL/RR/LR/RL 旋转',
      '        root = rotate(root)',
      '    return root',
    ],
    tips: 'LL: 左子树的左侧过重；RR: 右子树的右侧过重；LR/RL: 混合情况',
  },
  {
    id: 'avlSearch',
    name: 'AVL 树查询',
    category: 'tree',
    complexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(log n)' },
    description: 'AVL 树查询：利用 BST 左小右大的性质和平衡因子，每步折半查找目标，时间复杂度恒为 O(log n)。',
    code: [
      'function search(root, key):',
      '    while root != null:',
      '        if key == root.val:',
      '            return root  // 找到',
      '        if key < root.val:',
      '            root = root.left',
      '        else:',
      '            root = root.right',
      '    return null  // 未找到',
    ],
    tips: 'AVL 查询效率稳定，每次高度差 ≤ 1，保证 O(log n)',
  },
  {
    id: 'avlDelete',
    name: 'AVL 树删除',
    category: 'tree',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(log n)' },
    description: 'AVL 树删除：先执行标准 BST 删除，再沿删除路径向上回溯，每步更新高度并检查失衡，必要时旋转修复。',
    code: [
      'function delete(root, key):',
      '    // BST 标准删除',
      '    root = bstDelete(root, key)',
      '    // 回溯更新高度',
      '    while root != null:',
      '        updateHeight(root)',
      '        bf = height(left) - height(right)',
      '        if |bf| > 1:',
      '            root = rotate(root)  // 失衡修复',
      '        root = root.parent',
    ],
    tips: '删除可能导致多次失衡，每层最多一次旋转，总共 O(log n)',
  },
  // ==================== 红黑树 ====================
  {
    id: 'rbInsert',
    name: '红黑树插入',
    category: 'tree',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(log n)' },
    description: '红黑树插入：新建红色节点后，通过旋转和重新着色修复5条性质，包含叔节点红/黑的各种情况。',
    code: [
      'rbInsert(root, key):',
      '    z = Node(key, RED)',
      '    bstInsert(root, z)',
      '    while z.p.color == RED:',
      '        if z.p == z.p.p.left:',
      '            y = z.p.p.right  // 叔节点',
      '            if y.color == RED:  // 情况1',
      '                z.p.color = BLACK',
      '                y.color = BLACK',
      '                z.p.p.color = RED',
      '                z = z.p.p',
      '            else:  // 叔节点黑',
      '                if z == z.p.right:  // LR',
      '                    z = z.p; leftRotate(z)',
      '                z.p.color = BLACK',
      '                z.p.p.color = RED',
      '                rightRotate(z.p.p)',
      '        root.color = BLACK',
    ],
    tips: '根必为黑；红节点孩子必为黑；每条路径黑高相同',
  },
  {
    id: 'rbSearch',
    name: '红黑树查询',
    category: 'tree',
    complexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(log n)' },
    description: '红黑树查询：利用 BST 左小右大的性质，逐层比较查找目标值，与普通 BST 查询相同。',
    code: [
      'rbSearch(root, key):',
      '    while root != nil:',
      '        if key == root.val:',
      '            return root',
      '        if key < root.val:',
      '            root = root.left',
      '        else:',
      '            root = root.right',
      '    return nil',
    ],
    tips: '查询不改变树结构，时间复杂度 O(log n)',
  },
  {
    id: 'rbDelete',
    name: '红黑树删除',
    category: 'tree',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(log n)' },
    description: '红黑树删除：分三步——① BST 删除节点 ② 记录被删节点颜色 ③ DB(Double Black) 修复使黑高恢复平衡。',
    code: [
      'rbDelete(root, z):',
      '    y = z, y_orig = y.color',
      '    if z.left == nil:',
      '        x = z.right; transplant(root, z, z.right)',
      '    elif z.right == nil:',
      '        x = z.left; transplant(root, z, z.left)',
      '    else:',
      '        y = minimum(z.right)',
      '        y_orig = y.color',
      '        x = y.right',
      '        if y.p == z: x.p = y',
      '        else: transplant(root, y, y.right);',
      '               y.right = z.right; y.right.p = y',
      '        transplant(root, z, y)',
      '        y.left = z.left; y.left.p = y',
      '        y.color = z.color',
      '    if y_orig == BLACK:',
      '        rbDeleteFixUp(root, x)',
    ],
    tips: '删除黑色节点会导致黑高减少，需要 DB 修复（最多 O(log n) 次旋转）',
  },
  // ==================== 网络协议 ====================
  {
    id: 'tcpHandshake',
    name: 'TCP 三次握手',
    category: 'network',
    description: 'TCP 连接建立时，客户端与服务端交换三个报文段完成握手过程，确保双方就初始序列号达成一致。',
    tips: 'SYN 用于请求同步序列号；三次握手防止历史连接初始化混乱',
  },
  {
    id: 'tcpWave',
    name: 'TCP 四次挥手',
    category: 'network',
    description: 'TCP 连接关闭时，发送方和接收方各发送一次 FIN 并各确认一次 ACK，共四个报文段完全断开连接。',
    tips: '2MSL 等待确保被动关闭方收到最终 ACK；主动关闭方进入 TIME_WAIT 防止报文延迟到达',
  },
  // ==================== 最短路径算法 ====================
  {
    id: 'dijkstra',
    name: 'Dijkstra',
    category: 'graph',
    complexity: { best: 'O(E log V)', average: 'O(E log V)', worst: 'O(E log V)' },
    description: '单源最短路径算法（贪心），使用优先队列取最小距离节点，不支持负权边。',
    code: [
      'function dijkstra(graph, source):',
      '    dist[source] = 0',
      '    PQ = min-heap([source, 0])',
      '    while PQ not empty:',
      '        u = PQ.pop-min()',
      '        for each edge u→v with weight w:',
      '            if dist[u] + w < dist[v]:',
      '                dist[v] = dist[u] + w',
      '                PQ.push(v, dist[v])',
    ],
    tips: '不支持负权边；贪心选择当前最短，不回退',
  },
  {
    id: 'bellman-ford',
    name: 'Bellman-Ford',
    category: 'graph',
    complexity: { best: 'O(VE)', average: 'O(VE)', worst: 'O(VE)' },
    description: '单源最短路径，支持负权边。对所有边执行 n-1 轮松弛，第 n 轮检测负环。',
    code: [
      'function bellman-ford(graph, source):',
      '    dist[all] = ∞; dist[source] = 0',
      '    repeat n-1 times:',
      '        for each edge (u,v,w) in E:',
      '            if dist[u] + w < dist[v]:',
      '                dist[v] = dist[u] + w',
      '                prev[v] = u',
      '    // 第 n 轮检测负环',
      '    for each edge (u,v,w) in E:',
      '        if dist[u] + w < dist[v]:',
      '            return "Negative cycle detected"',
    ],
    tips: '支持负权边；可检测负环；时间复杂度 O(VE)',
  },
  {
    id: 'spfa',
    name: 'SPFA',
    category: 'graph',
    complexity: { best: 'O(E)', average: 'O(VE)', worst: 'O(VE)' },
    description: '队列优化的 Bellman-Ford，节点仅在距离更新后入队，避免无用松弛。',
    code: [
      'function spfa(graph, source):',
      '    dist[all] = ∞; queue = [source]',
      '    inQueue[source] = true',
      '    while queue not empty:',
      '        u = queue.pop()',
      '        inQueue[u] = false',
      '        for each edge u→v with weight w:',
      '            if dist[u] + w < dist[v]:',
      '                dist[v] = dist[u] + w',
      '                prev[v] = u',
      '                if not inQueue[v]:',
      '                    queue.push(v)',
      '                    inQueue[v] = true',
      '                    if inCount[v]++ > n:',
      '                        return "Negative cycle"',
    ],
    tips: '平均效率高于 Bellman-Ford；入队次数 > n 则有负环',
  },
  {
    id: 'floyd',
    name: 'Floyd-Warshall',
    category: 'graph',
    complexity: { best: 'O(V³)', average: 'O(V³)', worst: 'O(V³)' },
    description: '多源最短路径，动态规划 DP 表更新，求任意两点间最短路径。',
    code: [
      'function floyd-warshall(graph):',
      '    dist[i][j] = w(i,j) or ∞',
      '    for k = 0 to n-1:',
      '        for i = 0 to n-1:',
      '            for j = 0 to n-1:',
      '                if dist[i][k] + dist[k][j]',
      '                   < dist[i][j]:',
      '                    dist[i][j] =',
      '                    dist[i][k] + dist[k][j]',
    ],
    tips: '求多源最短路径；O(V³) 适合中小图；基于动态规划',
  },
  // ==================== 最小生成树算法 ====================
  {
    id: 'prim',
    name: 'Prim 算法',
    category: 'graph',
    complexity: { best: 'O(E log V)', average: 'O(E log V)', worst: 'O(E log V)' },
    description: 'Prim 算法：从某个起始节点出发，贪心地逐步扩展 MST，每次选取与当前树相连的最小权值边。',
    code: [
      'function prim(graph, start):',
      '    MST = {}, key[start] = 0',
      '    for each node v: key[v] = ∞',
      '    while MST 不完整:',
      '        u = 未加入MST中key最小的节点',
      '        将u加入MST',
      '        for each neighbor v of u:',
      '            if w(u,v) < key[v]:',
      '                key[v] = w(u,v)',
      '                parent[v] = u',
    ],
    tips: '类似 Dijkstra，但用 key[v] 记录到达 MST 的最小边权；适合稠密图',
  },
  {
    id: 'kruskal',
    name: 'Kruskal 算法',
    category: 'graph',
    complexity: { best: 'O(E log E)', average: 'O(E log E)', worst: 'O(E log E)' },
    description: 'Kruskal 算法：将所有边按权值升序排列，贪心地依次选取不形成环的最小边，用并查集判断是否成环。',
    code: [
      'function kruskal(graph):',
      '    将所有边按权值升序排序',
      '    初始化并查集，每个节点独立',
      '    MST = {}',
      '    for each edge (u,v,w) in sorted:',
      '        if find(u) != find(v):',
      '            MST.add((u,v,w))',
      '            union(u, v)',
      '        if |MST| == n-1: break',
    ],
    tips: '并查集用路径压缩+按秩合并达到近乎 O(1)；适合稀疏图',
  },
];

export function getAlgorithmById(id: string): AlgorithmInfo | undefined {
  return ALGORITHMS.find(a => a.id === id);
}

export function getAlgorithmsByCategory(category: 'sort' | 'search' | 'tree' | 'network' | 'graph'): AlgorithmInfo[] {
  return ALGORITHMS.filter(a => a.category === category);
}